<?php return array (
  'dbhost' => 'localhost',
  'dbuser' => 'root',
  'dbpass' => 'root',
  'qudong' => 'pdo',
  'dbport' => '3306',
  'charset' => 'UTF8',
  'dbtype' => 'mysql',
  'dbname' => 'miminong',
  'tabprefix' => 'mi_',
  'webhttp' => 'http://miminong.com',
  'webtitle' => '米米农|米农网|米表网|域名交易|域名发表',
  'description' => '米米农，提供专业的域名展示平台！一流的平台、一流的管理、一流的服务为您打造舒心适意的平台，时尚、刺激，米米农、魅力无穷。',
  'keywords' => '米米农,米农网,米表网, 域名交易,域名导航',
  'LOGO' => '/temp/image/20160409/20160409161013_54598.png',
  'email' => '69925844@qq.com',
  'icp' => ' 浙ICP备11545628号-3',
  'icpxx' => '版权所有   Copyright 2016 miminong.com',
  'census' => '',
);